# -*- coding: utf-8 -*-
"""calculate_precision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhNpbxqpq9bhFhG4N4e-pB-j2dm-ZKyT
"""

import argparse
import csv
from collections import Counter, defaultdict


def precision(counts):
    """Precision = correct / (correct + incorrect)."""
    reviewed = counts["1"] + counts["0"]
    return 100 * counts["1"] / reviewed if reviewed else None


def display_group(title, groups):
    print(f"\n{title}")
    print(f"{'Name':<26} {'Correct':>7} {'Incorrect':>9} {'Unreviewed':>10} {'Precision':>10}")
    for name, counts in sorted(groups.items()):
        score = precision(counts)
        score_text = f"{score:.2f}%" if score is not None else "N/A"
        print(f"{name:<26} {counts['1']:>7} {counts['0']:>9} {counts['']:>10} {score_text:>10}")

def display_dimensions(by_type):
    """Summarize counts and macro precision for the four dimensions."""
    dimensions = {
        "Meta-level": [
            "Study", "Person", "Organization"
        ],
        "Paper-specific": [
            "Experiment", "MLS_Task", "MLS_Dataset", "Method",
            "MLS_Model", "MLS_Algorithm", "Prompt", "MLS_Eval", "Measure"
        ],
        "Code-specific": [
            "SoftwareRepository", "MLS_Implementation", "Environment",
            "Dependency", "MLS_HyperParameter"
        ],
        "Provenance-related": [
            "DataSource", "DataProcessingStep", "TrainingRun",
            "EvaluationRun", "PredictionSet"
        ],
    }

    print("\nBy conceptual dimension")
    print(
        f"{'Dimension':<26} {'Correct':>7} {'Incorrect':>9} "
        f"{'Unreviewed':>10} {'Macro precision':>16}"
    )

    results = {}

    for dimension, entity_types in dimensions.items():
        totals = Counter()
        type_precisions = []

        for entity_type in entity_types:
            counts = by_type.get(entity_type, Counter())

            # Sum correct, incorrect, and unreviewed counts.
            totals.update(counts)

            # Average only types that have reviewed entities.
            score = precision(counts)
            if score is not None:
                type_precisions.append(score)

        macro_precision = (
            sum(type_precisions) / len(type_precisions)
            if type_precisions else None
        )

        score_text = (
            f"{macro_precision:.2f}%"
            if macro_precision is not None else "N/A"
        )

        print(
            f"{dimension:<26} {totals['1']:>7} {totals['0']:>9} "
            f"{totals['']:>10} {score_text:>16}"
        )

        results[dimension] = {
            "correct": totals["1"],
            "incorrect": totals["0"],
            "unreviewed": totals[""],
            "macro_precision": macro_precision,
        }

    # Identify entity types missing from the mapping.
    mapped_types = {
        entity_type
        for entity_types in dimensions.values()
        for entity_type in entity_types
    }
    unmapped = set(by_type) - mapped_types
    if unmapped:
        print("\nUnmapped entity types:", ", ".join(sorted(unmapped)))

    return results

overall = Counter()
by_document = defaultdict(Counter)
by_type = defaultdict(Counter)

# Read the CSV; ignore all other classification columns.
with open('/content/All_In_One_Paper_Entities_Refined.csv', encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        required = {"paper_id", "entity_type", "Abdel_classification"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing columns: {', '.join(sorted(missing))}")
        for row_number, row in enumerate(reader, start=2):
            label = (row["Abdel_classification"] or "").strip()
            if label not in {"1", "0", ""}:
                raise ValueError(f"Row {row_number}: unexpected Abdel_classification {label!r}")
            overall[label] += 1
            by_document[row["paper_id"]][label] += 1
            by_type[row["entity_type"]][label] += 1

print("Correctness source: Abdel_classification (1 = correct, 0 = incorrect)")
print(f"Total entities: {sum(overall.values())}")
print(f"Reviewed entities: {overall['1'] + overall['0']}")
print(f"Correct entities: {overall['1']}")
print(f"Incorrect entities: {overall['0']}")
print(f"Unreviewed entities: {overall['']}")
score = precision(overall)
print(f"Overall precision: {score:.2f}%" if score is not None else "Overall precision: N/A")
display_group("By document", by_document)
display_group("By entity type", by_type)
dimension_results = display_dimensions(by_type)
# A type error or an incorrect span is not automatically a hallucination.
# Recall/F1 require ground-truth totals and are not computed from these labels.