# -*- coding: utf-8 -*-
"""PDF Conversion Markdown

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19urs9kuoA4yvZ2odLM-AD6PSWwcjFPtl
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install 'markitdown[all]'

from markitdown import MarkItDown

# Initialize the MarkItDown converter
converter = MarkItDown()

# Specify the path to your PDF file
pdf_path = "/content/2504.19444.pdf"

# Convert the PDF to Markdown
result = converter.convert(pdf_path)

# Access the Markdown content
markdown_content = result.text_content

# Save the Markdown content to a file
with open("output.md", "w", encoding="utf-8") as md_file:
    md_file.write(markdown_content)

print("Conversion complete. Markdown saved to 'output.md'.")



!pip install pdfminer.six

!pip install pypdf

# importing required modules
from pypdf import PdfReader

# creating a pdf reader object
reader = PdfReader('/content/2004.14535.pdf')

# printing number of pages in pdf file
print(len(reader.pages))

# getting a specific page from the pdf file
page = reader.pages[6]

# extracting text from page
text = page.extract_text()
print(text)

!pip install PyMuPDF Pillow

# STEP 1
# import libraries
import fitz  # PyMuPDF
import io
from PIL import Image

# STEP 2
# file path you want to extract images from
file = "/content/1- 2005.00512v1.pdf"

# open the file
pdf_file = fitz.open(file)

# STEP 3
# iterate over PDF pages
for page_index in range(len(pdf_file)):

    # get the page itself
    page = pdf_file.load_page(page_index)  # load the page
    image_list = page.get_images(full=True)  # get images on the page

    # printing number of images found in this page
    if image_list:
        print(f"[+] Found a total of {len(image_list)} images on page {page_index}")
    else:
        print("[!] No images found on page", page_index)

    for image_index, img in enumerate(image_list, start=1):
        # get the XREF of the image
        xref = img[0]

        # extract the image bytes
        base_image = pdf_file.extract_image(xref)
        image_bytes = base_image["image"]

        # get the image extension
        image_ext = base_image["ext"]

        # save the image
        image_name = f"image{page_index+1}_{image_index}.{image_ext}"
        with open(image_name, "wb") as image_file:
            image_file.write(image_bytes)
            print(f"[+] Image saved as {image_name}")

!pip install docling

from docling.document_converter import DocumentConverter

source = "https://arxiv.org/pdf/2005.00512v1.pdf"  # document per local path or URL
converter = DocumentConverter()
result = converter.convert(source)
print(result.document.export_to_markdown())  # output: "## Docling Technical Report[...]"

!python pdf2md_batch.py /content/Input_PDFs